env:
    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    
task:
  name: "chidori-build"
  depends_on:
  - Test
  only_if: $CIRRUS_REPO_OWNER == 'CraftRom'
  persistent_worker:
    labels:
      name: BUILD
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 24
        memory: 120G
  Sync_script:
      - bash sync.sh
  Build_script:
      - bash build.sh
