env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    
task:
  name: "chidori-build"
  only_if: $CIRRUS_REPO_OWNER == 'CraftRom'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G
      
 Sync_script:
      - bash sync.sh

 Build_script:
      - bash build.sh

