


task:
  name: "Compile_Kernel"
  only_if: $CIRRUS_REPO_OWNER == 'CraftRom'
  timeout_in: 100m  
  container:
      image: stupidkidaf/kernel_docker:v1
      cpu: 4
      memory: 16G
      
  Sync_script:
      - cd ~
      - repo init -u https://github.com/CraftRom/kernel -b nightly
      - repo sync
      - for dev in onclite surya; do
      - mkdir -p chidori/$dev
      - (
      - cd chidori/$dev 
      - bash build.sh -n -t
      - )
      - done
