


task:
  name: "Compile_Kernel"
  only_if: $CIRRUS_REPO_OWNER == 'CraftRom'
  timeout_in: 100m  
  container:
      image: stupidkidaf/kernel_docker:v1
      cpu: 4
      memory: 16G
      
  Sync_script:
      - cd ~
      - sudo apt -y update
      - sudo apt-get -y install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev python python3 python-pip
      - git clone https://github.com/CraftRom/Chidori-Kernel_surya.git -b stable
      - cd Chidori-Kernel_surya
      - chmod a+x build.sh
      - bash build.sh
      - export kernel=$(ls *.zip)
      - curl -F document=@$kernel "https://api.telegram.org/bot1472514287:AAEGegABAhV5RfK7Q8aoIs-lzLlLu3w1aQ4/sendDocument" \
        -F chat_id=-1452770277 \
        -F "disable_web_page_preview=true" \
        -F "parse_mode=html" \
        -F caption="New update available for <b>POCO X3</b> based on Linux <b>$(cat $(pwd)/out/.config | grep Linux/arm64 | cut -d " " -f3)</b> at commit $(git log --pretty=format:"%h (\"%s\")" -1))"