env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    
task:
  name: "chidori-build"
  only_if: $CIRRUS_REPO_OWNER == 'CraftRom'
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G
  Sync_script:
      - bash sync.sh
  Build_script:
      - bash build.sh
