


task:
  name: "Compile_Kernel"
  only_if: $CIRRUS_REPO_OWNER == 'CraftRom'
  timeout_in: 100m  
  container:
      image: stupidkidaf/kernel_docker:v1
      cpu: 32
      memory: 64G
      
  Sync_script:
      - bash build.sh
